apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
spec:
  template:
    spec:
      containers:
        - name: k6
          image: loadimpact/k6
          command: ["sh", "-c", "k6 run /scripts/load-test.js"]
          volumeMounts:
            - name: k6-script
              mountPath: /scripts
      restartPolicy: Never
      volumes:
        - name: k6-script
          configMap:
            name: k6-load-test
  backoffLimit: 4
