apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helmchart.s3.amazonaws.com/charts'
    chart: 'BlogDashborad-chart'
    targetRevision: HEAD  # Use the latest version
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      # Enable auto-sync for automatic updates
      syncOptions:
        - CreateNamespace=true
