auth:
  image: docker.io/kpblm256/aiq-backend:1.2.1
  imagePullPolicy: Always
  replicas: 1
  port: 4000
  targetPort: 4000
  restartPolicy: Always
  env:
    - name: MONGO
      value: mongodb+srv://admin:XAIetDKFKKvNAxLB@dbguru.8blhy1f.mongodb.net/dbguru?retryWrites=true&w=majority&appName=dbguru
    - name: JWT_SECRET
      value: sdjfslgjd56fr7