name: Build, Deploy, and Sync S3

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy_infra:
        description: 'Destroy Infrastructure'
        required: true
        default: false
        type: boolean

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.destroy_infra == false }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./infra
        
      - name: Apply Terraform
        id: apply_terraform
        run: terraform apply -auto-approve
        working-directory: ./infra
        
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.destroy_infra == false }}
    needs: terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          
      - name: Install dependencies and build
        run: |
          cd client
          npm install
          npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: client/dist

  upload_to_s3:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.destroy_infra == false }}
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: client-build
          path: client/dist
          
      - name: Sync to S3
        run: |
          aws s3 sync client/dist s3://aiq-frontend --acl public-read --delete

  destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.destroy_infra == true }}
    needs: []
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./infra
        
      - name: Destroy Terraform resources
        run: terraform destroy -auto-approve
        working-directory: ./infra
