name: Docker Build and Push
on:
  # push:
  #   branches:
  #     - feature/CI
  push:
    tags:
      - "v*"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./api/auth/Dockerfile
            image: aiq-auth
            context: ./api/auth
          - dockerfile: ./api/user/Dockerfile
            image: aiq-user
            context: ./api/user
          - dockerfile: ./api/post/Dockerfile
            image: aiq-post
            context: ./api/post
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker Images
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}