name: Release Helm Chart

on:
  push:
    branches:
      - gh-pages

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Package Helm chart
      run: helm package k8s/BlogDashboard-chart --destination .deploy

    - name: Publish to GitHub Pages
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        cd .deploy
        git init
        git remote add origin https://x-access-token:${{ secrets.GITHUBTAG }}@ki-blog.github.io/BlogMitDashboard
        helm repo index . --url https://ki-blog.github.io/BlogMitDashboard/
        git add .
        git commit -m "Release $(git describe --tags)"
        git push origin gh-pages --force

    - name: Clean up
      run: rm -rf .deploy
