name: Release Helm Chart

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Package Helm chart
      run: helm package k8s/BlogDashboard-chart --destination .deploy

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create GitHub Pages branch if not exists
      run: |
        git remote add upstream https://github.com/Ki-Blog/HelmChart.git
        git fetch upstream gh-pages
        if git show-ref --quiet refs/heads/gh-pages; then
          echo "gh-pages branch already exists"
        else
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "feat: Initial commit on gh-pages branch"
          git push https://x-access-token:${{ secrets.GITHUBTAG }}@github.com/Ki-Blog/HelmChart.git gh-pages
        fi

    - name: Checkout gh-pages branch
      run: |
        git checkout gh-pages
        git pull https://x-access-token:${{ secrets.GITHUBTAG }}@github.com/Ki-Blog/HelmChart.git gh-pages

    - name: Move new chart package
      run: mv .deploy/*.tgz .

    - name: Generate Helm repo index
      run: helm repo index . --url https://Ki-Blog.github.io/HelmChart/

    - name: Add and commit changes
      run: |
        git add .
        git commit -m "feat: Publish new Helm chart"

    - name: Push changes to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTAG }}
      run: |
        git pull https://x-access-token:${{ secrets.GITHUBTAG }}@github.com/Ki-Blog/HelmChart.git gh-pages --rebase
        git push https://x-access-token:${{ secrets.GITHUBTAG }}@github.com/Ki-Blog/HelmChart.git gh-pages --force

    - name: Clean up
      run: rm -rf .deploy
