name: Cypress Tests

on:
    push:
     branches:
      - feature/cypress
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
        working-directory: ./e2e-testing
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
         command: npx cypress run
         browser: chrome
      working-directory: ./e2e-testing
      