name: Terraform Apply

on:
#   push:
#     tags:
#       - "v*"
  push:
    branches:
      - feature/CI

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}


      - name: Initialize Terraform
        run: terraform init
        working-directory: ./infra_back

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./infra_back

      - name: Confirm Apply
        run: terraform apply tfplan
        working-directory: ./infra_back
        env:
          TF_CLI_AUTO_APPROVE: 1